import Head from 'next/head'
import Link from 'next/link'
import React from 'react';
import AccordionHome from '../components/AccordionHome'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ratton Springs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className="max-w-full bg-hero-home bg-cover h-xl bg-center flex items-center justify-center">
        <h1 className="text-white text-5xl">
          Welcome to Ratton Springs
        </h1>
      </section>

    <section className="flex items-center mt-9 mx-40">
      <div className="flex2 pr-44">
        <p>Ratton Springs is a global beverage company leading the international market.
          Exercitation in fugiat est ut ad ea cupidatat ut in
          cupidatat occaecat ut occaecat consequat est minim minim
          esse tempor laborum consequat esse adipisicing eu
          reprehenderit enim.</p>
        <h2 className="py-7">Find out more about our products and services!</h2>
        <AccordionHome />
      </div>
      <div className="flex1">
        <img src="../images/hands-with-water.jpg" alt="water splashing on hands"/>
      </div>
    </section>


      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </>
  )
}
